// Persistent deviceId for this Linux box.
//
// Lives at ~/.yome/device.json (0600), same dir as the auth.json that
// yome login writes. Generated once on first `yome mesh start`, never
// rotated unless the user explicitly removes the file.
//
// Strategy choice (see cli/MIGRATION.md): self-generated UUID, NOT
// /etc/machine-id hash. Reason: VM templates and Docker images are
// frequently cloned, and machine-id collisions would silently merge two
// servers in the mesh device list. Random UUID is collision-safe across
// clones; if a user really wants to keep a stable id when re-imaging,
// they can copy ~/.yome/device.json over.
//
// Matches macOS/iOS behaviour in Yome/Shared/Sync/DeviceRegistrar.swift
// (UUID stored in Keychain SecureStore).

import {
  existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync,
} from 'fs';
import { homedir, hostname as osHostname, platform, release } from 'os';
import { join, dirname } from 'path';
import { randomUUID } from 'crypto';

export interface DeviceState {
  /** UUID v4 generated by this cli on first run. */
  deviceId: string;
  /** ISO-8601 timestamp of first generation. */
  createdAt: string;
  /** Hostname captured at first run, for logs / debugging. */
  initialHostname: string;
  /** Optional human-friendly name. Set via `yome mesh rename <alias>`. */
  alias?: string;
  /** Optional long-form description. */
  description?: string;
}

export function getDeviceFilePath(): string {
  return join(homedir(), '.yome', 'device.json');
}

export function loadDeviceState(): DeviceState | null {
  const f = getDeviceFilePath();
  if (!existsSync(f)) return null;
  try {
    const obj = JSON.parse(readFileSync(f, 'utf-8'));
    if (typeof obj?.deviceId !== 'string') return null;
    return obj as DeviceState;
  } catch {
    return null;
  }
}

export function writeDeviceState(state: DeviceState): void {
  const f = getDeviceFilePath();
  mkdirSync(dirname(f), { recursive: true });
  writeFileSync(f, JSON.stringify(state, null, 2) + '\n', { mode: 0o600 });
  // mode in writeFileSync only applies on CREATE; chmod again to be sure.
  try { chmodSync(f, 0o600); } catch { /* best effort on Windows */ }
}

/**
 * Return the persistent deviceId, creating ~/.yome/device.json on first
 * call. Idempotent + safe to call from any subcommand.
 */
export function getOrCreateDeviceId(): string {
  const existing = loadDeviceState();
  if (existing) return existing.deviceId;
  const fresh: DeviceState = {
    deviceId: randomUUID(),
    createdAt: new Date().toISOString(),
    initialHostname: safeHostname(),
  };
  writeDeviceState(fresh);
  return fresh.deviceId;
}

/** Update alias + description; preserves deviceId / createdAt. */
export function updateDeviceMeta(meta: { alias?: string; description?: string }): DeviceState {
  const current = loadDeviceState();
  if (!current) {
    // First run + rename in one shot: still generate the deviceId.
    const fresh: DeviceState = {
      deviceId: getOrCreateDeviceId(),
      createdAt: new Date().toISOString(),
      initialHostname: safeHostname(),
      alias: meta.alias,
      description: meta.description,
    };
    writeDeviceState(fresh);
    return fresh;
  }
  const next: DeviceState = { ...current };
  if (meta.alias !== undefined) next.alias = meta.alias;
  if (meta.description !== undefined) next.description = meta.description;
  writeDeviceState(next);
  return next;
}

export function getModelString(): string {
  // Format chosen to mirror DeviceRegistrar.swift's "{hwModel}, macOS {ver}"
  // shape so the device list in iOS/macOS reads consistently.
  // Linux: "{kernel-release}, {hostname}" — no useful "hw.model" sysctl
  // equivalent on a generic VM; we'd otherwise have to parse
  // /sys/class/dmi/id/product_name which most cloud VMs forge or hide.
  return `Linux ${release()}`;
}

export function safeHostname(): string {
  try {
    return osHostname();
  } catch {
    return 'linux-host';
  }
}

export function currentPlatform(): NodeJS.Platform {
  return platform();
}
